required:
  - type
  - text
properties:
  type:
    type: string
    description: >-
      The action type. See [**ActionTypeEnum**](Enums.md#ActionTypeEnum) for
      available values.
  text:
    type: string
    description: The button text.
  payload:
    type: string
    description: |
      The payload to be sent with the resulting webhook.
      Required for *postback* and *reply* actions.
  metadata:
    type: object
    description: >-
      Flat JSON object containing any custom properties associated with the
      action.
  amount:
    type: integer
    description: >
      The amount being charged. It needs to be specified in cents and is an
      integer.

      Required for *buy* actions.
  currency:
    type: string
    description: 'The currency of the amount being charged (USD, CAD, etc.).'
  default:
    type: boolean
    description: >-
      Flag indicating if the message action is the default for a message item in
      Facebook Messenger.
  iconUrl:
    type: string
    description: >-
      An icon to render next to the reply option (Facebook Messenger and Web
      Messenger only).
  uri:
    type: string
    description: >
      The action URI. This is the link that will be used in the clients when
      clicking the button.

      Required for *link* and *webview* actions.
  fallback:
    type: string
    description: >
      The webview action fallback uri. This is the link that will be used in
      clients that do not support webviews.

      Required for *webview* actions.
  size:
    type: string
    description: >
      The size used to display the webview. Allowed values are ["compact",
      "tall", "full"].

      (Optional) Used for *webview* actions. See
      [**ActionSizeEnum**](Enums.md#ActionSizeEnum) for available values.
  extraChannelOptions:
    type: object
    description: >-
      Extra options to pass directly to the channel API. See [Extra Channel
      Options](https://docs.smooch.io/rest#extra-channel-options-schema)
  openOnReceive:
    type: boolean
    description: >-
      Flag indicating if the webview should open automatically. Only one action
      per message can be set to true. Currently only supported on the Web
      Messenger.
