required:
  - _id
  - appToken
  - name
type: object
properties:
  _id:
    type: string
    description: The app's ID.
  appToken:
    type: string
    description: >-
      The appToken, used to initialize the Web, iOS and Android clients and to
      make calls to the app user facing API.
  name:
    type: string
    description: The app's name.
  settings:
    type: object
    description: Customizable app settings.
    properties:
      maskCreditCardNumbers:
        type: boolean
        description: >-
          Flag specifying whether credit card numbers will be automatically
          masked if sent through Smooch.
      useAnimalNames:
        type: boolean
        description: >-
          Flag specifying whether animal names should be used for anonymous
          users.
      conversationRetentionSeconds:
        type: integer
        description: >-
          Number of seconds of inactivity before a conversation’s messages will
          be automatically deleted.
      echoPostback:
        type: boolean
        description: >-
          A boolean specifying whether a message should be added to the
          conversation history when a postback button is clicked.
      ignoreAutoConversationStart:
        type: boolean
        description: >-
          A boolean specifying whether a non message event coming from a social
          channel will trigger a start conversation event and count as an active
          user conversation (AUC).<br>**Note:** Calling *startConversation()*
          (or equivalent) from the Android-, iOS- or Web-SDK will count as an
          AUC, regardless of the value of this setting.
  metadata:
    type: object
    description: Flat JSON object containing any custom properties associated with the app.
