type: object
required:
  - _id
  - status
  - hosting
properties:
  _id:
    type: string
    description: 'The deployment ID, generated automatically.'
  status:
    type: string
    description: >-
      The deployment status. See
      [**DeploymentStatusEnum**](Enums.md#DeploymentStatusEnum) for available
      values.
  hosting:
    type: string
    description: >-
      The deployment hosting. See
      [**DeploymentHostingEnum**](Enums.md#DeploymentHostingEnum) for available
      values.
  baseUrl:
    type: string
    description: The baseUrl of the deployment. Only present for `self` hosted deployments.
  username:
    type: string
    description: >-
      The username of the deployment. Only present for `self` hosted
      deployments.
  phoneNumber:
    type: string
    description: >-
      The phoneNumber of the deployment. Only present once the deployment has
      been registered.
  callbackUrl:
    type: string
    description: The URL to be called by Smooch when the status of the deployment changes.
  callbackSecret:
    type: string
    description: The secret used to secure the callback.
  integrationId:
    type: string
    description: The integrationId of the integration using this deployment.
  appId:
    type: string
    description: The appId of the integration using this deployment.
