type: object
properties:
  imageAspectRatio:
    type: string
    description: >-
      Specifies how to display all carousel images. See
      [**ImageAspectRatioEnum**](Enums.md#ImageAspectRatioEnum) for available
      values.
